export const galleryImages = [
  { filename: "img1.jpeg", category: "campus", title: "Campus View 1", alt: "Main campus entrance and landscaping of Kualakubs World School" },
  { filename: "img2.jpeg", category: "campus", title: "Campus View 2", alt: "Well-lit and ventilated modern classroom layout" },
  { filename: "img3.jpeg", category: "campus", title: "Campus View 3", alt: "Spacious corridors and indoor transition zones" },
  { filename: "img4.jpeg", category: "campus", title: "Campus View 4", alt: "Safety and security desk at the school entrance" },
  { filename: "img5.jpeg", category: "campus", title: "Campus View 5", alt: "Green areas and playground zones on the campus" },
  { filename: "img6.jpeg", category: "academic", title: "Academic Session 1", alt: "Students working on experiments in the Science Lab" },
  { filename: "img7.jpeg", category: "academic", title: "Academic Session 2", alt: "Active learning session inside a smart classroom" },
  { filename: "img8.jpeg", category: "academic", title: "Academic Session 3", alt: "Makers and Innovation Lab with robotics equipment" },
  { filename: "img9.jpeg", category: "academic", title: "Academic Session 4", alt: "Reading session in the well-stocked school library" },
  { filename: "img10.jpeg", category: "academic", title: "Academic Session 5", alt: "Group discussion session on a project" },
  { filename: "img11.jpeg", category: "sports", title: "Sports Activity 1", alt: "Students playing soccer on the sports field" },
  { filename: "img12.jpeg", category: "sports", title: "Sports Activity 2", alt: "Track and field athletics event during sports meet" },
  { filename: "img13.jpeg", category: "sports", title: "Sports Activity 3", alt: "Indoor sports and physical education room activities" },
  { filename: "img14.jpeg", category: "sports", title: "Sports Activity 4", alt: "Basketball practice session on the outdoor court" },
  { filename: "img15.jpeg", category: "sports", title: "Sports Activity 5", alt: "Yoga and wellness session on the green lawn" },
  { filename: "img16.jpeg", category: "events", title: "School Event 1", alt: "Annual day stage performance by students" },
  { filename: "img17.jpeg", category: "events", title: "School Event 2", alt: "Special school assembly celebrating national festival" },
  { filename: "img18.jpeg", category: "events", title: "School Event 3", alt: "Art exhibition showing student artworks" },
  { filename: "img19.jpeg", category: "events", title: "School Event 4", alt: "Community service program run by student council" },
  { filename: "img20.jpeg", category: "events", title: "School Event 5", alt: "Science exhibition presentation by school students" },
  { filename: "img21.jpg", category: "HealthCamp", title: "Health Camp", alt: "Students participating in a health awareness camp at Kualakubs World School" },
  { filename: "img22.jpg", category: "HealthCamp", title: "Health Camp", alt: "Medical professionals conducting health checkups for students at Kualakubs World School" },
  { filename: "img23.jpg", category: "HealthCamp", title: "Health Camp", alt: "Health camp session focused on student wellness at Kualakubs World School" },
  { filename: "img24.jpg", category: "HealthCamp", title: "Health Camp", alt: "Students receiving basic health screening during the health camp at Kualakubs World School" },
  { filename: "img25.jpg", category: "HealthCamp", title: "Health Camp", alt: "Doctors interacting with students during a health camp at Kualakubs World School" },
  { filename: "img26.jpg", category: "HealthCamp", title: "Health Camp", alt: "Health awareness activities organized for students at Kualakubs World School" },
  { filename: "img27.jpeg", category: "HealthCamp", title: "Health Camp", alt: "Medical examination and wellness guidance provided at Kualakubs World School health camp" },
  { filename: "img28.jpeg", category: "HealthCamp", title: "Health Camp", alt: "Students learning about healthy lifestyle practices during a health camp at Kualakubs World School" },
  { filename: "img29.jpeg", category: "HealthCamp", title: "Health Camp", alt: "Healthcare experts offering preventive health advice to students at Kualakubs World School" },
  { filename: "img30.jpeg", category: "HealthCamp", title: "Health Camp", alt: "School health camp promoting fitness and well-being among students at Kualakubs World School" },
  { filename: "img31.jpeg", category: "HealthCamp", title: "Health Camp", alt: "Students and staff attending a comprehensive health camp at Kualakubs World School" },
  { filename: "img32.jpeg", category: "HealthCamp", title: "Health Camp", alt: "Health camp initiative supporting student health and wellness at Kualakubs World School" },
  { filename: "img33.jpg", category: "events", title: "School Event 6", alt: "Students participating in a special school event at Kualakubs World School" },
  { filename: "img34.jpg", category: "events", title: "School Event 7", alt: "School community gathering during an educational event at Kualakubs World School" },
  { filename: "img35.jpg", category: "events", title: "School Event 8", alt: "Students showcasing their talents at a school event at Kualakubs World School" },
  { filename: "img36.jpg", category: "events", title: "School Event 9", alt: "Interactive student activities during a school event at Kualakubs World School" },
  { filename: "img37.jpg", category: "events", title: "School Event 10", alt: "Students engaging in collaborative learning during a school event at Kualakubs World School" },
  { filename: "img38.jpg", category: "events", title: "School Event 11", alt: "Celebration and participation of students in a school event at Kualakubs World School" },
  { filename: "img39.jpg", category: "events", title: "School Event 12", alt: "Creative performances by students during a school event at Kualakubs World School" },
  { filename: "img40.jpg", category: "events", title: "School Event 13", alt: "Students enjoying educational and cultural activities at Kualakubs World School" },
  { filename: "img41.jpg", category: "events", title: "School Event 14", alt: "School event highlighting student achievements at Kualakubs World School" },
  { filename: "img42.jpg", category: "events", title: "School Event 15", alt: "Students participating enthusiastically in a school celebration at Kualakubs World School" },
  { filename: "img43.jpg", category: "events", title: "School Event 16", alt: "Educational event fostering creativity and teamwork at Kualakubs World School" },
  { filename: "img44.jpg", category: "events", title: "School Event 17", alt: "Memorable moments from a student-focused school event at Kualakubs World School" },
  { filename: "img45.jpg", category: "events", title: "School Event 18", alt: "Students and teachers celebrating a successful school event at Kualakubs World School" },
];
